apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      labels:
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: arjunkrsharma/finance-app:v1
        ports:
        - containerPort: 5000
